# on:
#   push:
#     branches: master
# every morning at 8:00h (UTC+2)
on:
  schedule:
  - cron: "17 3 * * *"
  workflow_dispatch:

jobs:
  run-birthday-bot:
    runs-on: ubuntu-latest
    container: rocker/tidyverse:4.4.2
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      INIMS_SHEETS_BIRTHDAYS: ${{ secrets.INIMS_SHEETS_BIRTHDAYS }}
      INIMS_SHEETS_GOOGLE_MAIL: ${{ secrets.INIMS_SHEETS_GOOGLE_MAIL }}
      INIMS_SLACK_HOOK_BIRTHDAY_SOCIAL: ${{ secrets.INIMS_SLACK_HOOK_BIRTHDAY_SOCIAL }}
      INIMS_SLACK_HOOK_BIRTHDAY_TEST: ${{ secrets.INIMS_SLACK_HOOK_BIRTHDAY_TEST }}

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          for i in 1 2 3; do
            apt-get update && apt-get install -y curl gnupg && break || sleep 15
          done

      - name: Decrypt large secret
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$ENCYRPTION_PASSPHRASE" --output ./inims_sheets.json ./inims_sheets.json.gpg
        env:
          ENCYRPTION_PASSPHRASE: ${{ secrets.ENCYRPTION_PASSPHRASE }}

      - name: Install packages
        run: |
          remotes::install_cran("stringi")
          remotes::install_cran("googlesheets4")
        shell: Rscript {0}

      - name: Run script
        run: |-
          Rscript R/birthday_bot.R
