# on:
#   push:
#     branches: master
# every morning at 8:00h (UTC+2)
on:
  schedule:
  - cron: "0 5 * * *"

jobs:
  run-nobel-bot:
    runs-on: ubuntu-20.04
    container: rocker/tidyverse:4.2.1
    env:
      INIMS_SHEETS_BIRTHDAYS: ${{ secrets.INIMS_SHEETS_BIRTHDAYS }}
      INIMS_SHEETS_GOOGLE_MAIL: ${{ secrets.INIMS_SHEETS_GOOGLE_MAIL }}
      INIMS_SLACK_HOOK_NOBEL_TEST: ${{ secrets.INIMS_SLACK_HOOK_NOBEL_TEST }}
      INIMS_SLACK_HOOK_NOBEL_NOBEL: ${{ secrets.INIMS_SLACK_HOOK_NOBEL_NOBEL }}

    steps:
      - uses: actions/checkout@v2

      - name : Update
        run: apt-get update

      - name: Install curl
        run: apt-get install -y curl

      - name: Install gpg
        run: apt-get install -y gnupg2

      # - name: Decrypt large secret
      #   run: |
      #     gpg --quiet --batch --yes --decrypt --passphrase="$ENCYRPTION_PASSPHRASE" --output ./rrutweets-sheet.json ./rrutweets-sheet.json.gpg
      #   env:
      #     ENCYRPTION_PASSPHRASE: ${{ secrets.ENCYRPTION_PASSPHRASE }}

      - name: Install packages
        run: |
          remotes::install_cran("stringi")
          remotes::install_cran("googlesheets4")
        shell: Rscript {0}

      - name: Run script
        run: |-
          Rscript R/nobel_bot.R
